development:
  adapter: postgresql
  encoding: utf8
  database: climate
  username: stas
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: utf8
  database: climate
  username: stas
  host: 127.0.0.1

